name: SightLock
version: ${version}
main: com.github.kdy05.sightLock.SightLock
api-version: '1.21'
authors: [ Ararab ]
description: Lock the entity in your sight!
website: https://github.com/KDY05
commands:
  sightlock:
    description: main command
    aliases: [sl]
    permission: sightlock.use
permissions:
  sightlock.use:
    description: Allows using the basic commands
    default: op
  sightlock.reload:
    description: Allows reloading configurations
    default: op